version: '3.3'
services:
  apiso:
      build: .
      networks:
        - project-network
      ports:
        - "8080:8080"
      restart: always
      environment:
        BUCKET_NAME: 
        REGION_NAME: 
networks:
  project-network:
    driver: bridge
  