apiVersion: v1
kind: Service
metadata:
  name: placeholder-app-service
  namespace: prd
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: false
  labels:
    app: placeholder-app
spec:
  type: LoadBalancer
  ports:
  # Inside the cluster, what port does the service expose?
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
      app: placeholder-app
